### ISSUE TITLE
Incorrect error message

### ISSUE THREAD

**Issue by uranusjr** [uranusjr/pyem#12]
```console
$ pyem --version
pyem 2.0.0b2
$ pyem --project . venv add 3.5
Traceback (most recent call last):
  File "/home/uranusjr/.local/bin/pyem", line 8, in <module>
    sys.exit(main())
  File "/home/uranusjr/.local/pipx/venvs/pyem/lib/python3.8/site-packages/pyem/__init__.py", line 10, in main
    return dispatch(None)
  File "/home/uranusjr/.local/pipx/venvs/pyem/lib/python3.8/site-packages/pyem/cmds.py", line 192, in dispatch
    return opts.func(project, opts)
  File "/home/uranusjr/.local/pipx/venvs/pyem/lib/python3.8/site-packages/pyem/venvs.py", line 16, in add
    runtime = project.create_runtime(options.python)
  File "/home/uranusjr/.local/pipx/venvs/pyem/lib/python3.8/site-packages/pyem/projects/runtimes.py", line 245, in create_runtime
    env_name = get_interpreter_quintuplet(python)
  File "/home/uranusjr/.local/pipx/venvs/pyem/lib/python3.8/site-packages/pyem/projects/envs.py", line 110, in get_interpreter_quintuplet
    return _get_command_output([os.fspath(python), "-c", _VENV_NAME_CODE])
  File "/home/uranusjr/.local/pipx/venvs/pyem/lib/python3.8/site-packages/pyem/projects/envs.py", line 20, in _get_command_output
    return subprocess.check_output(args, text=True, **kwargs).strip()
  File "/home/uranusjr/.local/share/pythonup/versions/3.8/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/uranusjr/.local/share/pythonup/versions/3.8/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/uranusjr/.local/share/pythonup/versions/3.8/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/uranusjr/.local/share/pythonup/versions/3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/uranusjr/Documents/programming/cytcpro-cloud/No executable found for Python 3.5'
```

**Comment by uranusjr** [comment]
Fixed in a38f835a1106948cbf25d6a24970406203ac12bf.
